# ruff: noqa: E501
"""Creation workspace tool declarations."""

from __future__ import annotations

from app.architecture.tool_definition import ToolDef

TOOL_DEFINITIONS: tuple[ToolDef, ...] = (
    ToolDef(
        name="design_plot",
        description="设计完整章节剧情——含场景拆解、角色行为、冲突张力、情绪曲线、一致性检查等7个维度。用户说'设计剧情''这章怎么写'时使用。",
        input_schema={
            "outline_node_id": {"type": "string", "description": "关联的大纲节点ID，可选"},
            "involved_characters": {
                "type": "array",
                "items": {"type": "string"},
                "description": "出场的角色名或ID列表，可选",
            },
            "requirements": {"type": "string", "description": "用户的额外要求，可选"},
            "feedback": {"type": "string", "description": "对上一轮设计的反馈（迭代时使用），可选"},
            "previous_plot": {
                "type": "string",
                "description": "上一轮设计的剧情（迭代时使用），可选",
            },
        },
        tool_type="analysis",
        estimated_cost="medium",
        handler_name="design_plot",
    ),
    ToolDef(
        name="chapter_writer",
        description="使用模型已经检索、复核并由服务端精确校验的上下文，生成一份未入库的新章或已有章节修订候选；不会自动覆盖正式正文。修订时必须传与所选大纲匹配的 target_chapter_id。必须先 prepare_task_context、按需 search_task_context、submit_context_evidence，并在下一模型步骤携带返回的选择令牌。成功后本轮结束。",
        input_schema={
            "outline_node_id": {"type": "string", "description": "对应的大纲节点ID（必填）"},
            "target_chapter_id": {
                "type": "string",
                "description": "修订已有正式章节时必填；必须是所选大纲当前关联的章节ID",
            },
            "context_manifest_id": {
                "type": "string",
                "description": "prepare_task_context 返回的写章清单ID",
            },
            "context_selection_token": {
                "type": "string",
                "description": "submit_context_evidence 成功后返回的一次性选择令牌；必须在后续模型步骤使用",
            },
        },
        required=["outline_node_id", "context_manifest_id", "context_selection_token"],
        tool_type="generator",
        estimated_cost="high",
        handler_name="chapter_writer",
    ),
    ToolDef(
        name="character_writer",
        description="生成角色卡片。加载完整角色设计规则（深度、一致性、反套路），根据项目上下文和用户要求创造出立体、有记忆点的角色。创建角色前必须先调用此工具生成角色卡片。",
        input_schema={
            "name": {"type": "string", "description": "角色名（可选，不传则由AI生成）"},
            "role_type": {
                "type": "string",
                "enum": ["protagonist", "supporting", "antagonist", "mentor", "other"],
                "description": "建议角色类型：protagonist|supporting|antagonist|mentor|other",
            },
            "requirements": {"type": "string", "description": "用户对角色的要求或方向（可选）"},
        },
        tool_type="generator",
        estimated_cost="high",
        handler_name="character_writer",
    ),
    ToolDef(
        name="outline_writer",
        description="使用模型已检索、复核并由服务端精确校验的上下文，生成一份持久化但未写入正式大纲的提案；不会自动读取全量大纲、角色或世界观。必须先 prepare_task_context(task_type=outline_planning)、按需检索、submit_context_evidence，并携带一次性令牌。成功后本轮结束，由作者编辑、确认或丢弃。",
        input_schema={
            "parent_id": {"type": "string", "description": "父节点ID（可选）"},
            "insert_after_id": {"type": "string", "description": "同级插入锚点ID（可选）"},
            "requirements": {"type": "string", "description": "用户对大纲的要求或方向（可选）"},
            "batch_count": {"type": "integer", "description": "生成节点数量，默认1，上限8"},
            "context_manifest_id": {
                "type": "string",
                "description": "prepare_task_context 返回的大纲规划清单ID",
            },
            "context_selection_token": {
                "type": "string",
                "description": "submit_context_evidence 返回的一次性选择令牌",
            },
        },
        required=["context_manifest_id", "context_selection_token"],
        tool_type="generator",
        estimated_cost="high",
        handler_name="outline_writer",
    ),
    ToolDef(
        name="worldbuilding_writer",
        description="生成世界观设定条目。加载维度专属设计规则（地理/历史/势力/规则体系/种族/文化），创造有深度、逻辑自洽、服务于剧情的世界观设定。创建世界观前应先调用此工具生成设定。",
        input_schema={
            "dimension": {
                "type": "string",
                "description": "维度：geography|history|factions|power_system|races|culture，默认culture",
            },
            "title": {"type": "string", "description": "建议标题（可选）"},
            "requirements": {"type": "string", "description": "用户对设定的要求或方向（可选）"},
        },
        tool_type="generator",
        estimated_cost="high",
        handler_name="worldbuilding_writer",
    ),
    ToolDef(
        name="rewrite_text",
        description="按指定风格改写文本。自动修复禁用句式。用户说'改写''重写''润色'时使用。",
        input_schema={
            "text": {"type": "string", "description": "要改写的原文"},
            "style": {
                "type": "string",
                "description": "目标风格：vivid|concise|serious|humorous|poetic，可选",
            },
            "prompt": {"type": "string", "description": "额外的改写要求，可选"},
        },
        required=["text"],
        tool_type="generator",
        estimated_cost="low",
        handler_name="rewrite_text",
    ),
    ToolDef(
        name="expand_text",
        description="扩充文本细节。自动修复禁用句式。用户说'扩写''丰富''展开'时使用。",
        input_schema={
            "text": {"type": "string", "description": "要扩写的原文"},
            "prompt": {"type": "string", "description": "扩写方向提示，可选"},
        },
        required=["text"],
        tool_type="generator",
        estimated_cost="low",
        handler_name="expand_text",
    ),
    ToolDef(
        name="continue_text",
        description="从指定文本结尾处继续写作。自动修复禁用句式。用户说'续写''继续写'时使用。",
        input_schema={
            "text": {"type": "string", "description": "上文内容"},
            "outline_node_id": {"type": "string", "description": "关联的大纲节点ID，可选"},
            "prompt": {"type": "string", "description": "续写方向提示，可选"},
        },
        required=["text"],
        tool_type="generator",
        estimated_cost="low",
        handler_name="continue_text",
    ),
    ToolDef(
        name="roleplay_character",
        description="让单个角色对场景做出回应（对话/动作/内心独白）。AI扮演该角色，结果可直接用于章节正文。",
        input_schema={
            "character_id": {"type": "string", "description": "角色ID（优先使用）"},
            "character_name": {"type": "string", "description": "角色名（character_id为空时使用）"},
            "situation": {"type": "string", "description": "场景描述——告诉角色当前发生了什么"},
            "outline_node_id": {"type": "string", "description": "关联的大纲节点ID，可选"},
        },
        required=["situation"],
        tool_type="generator",
        estimated_cost="medium",
        handler_name="roleplay_character",
    ),
    ToolDef(
        name="dialogue_battle",
        description="多个角色按回合制对戏。每个角色依次发言并承接上文，适用于需要自然对话的场景。",
        input_schema={
            "character_names": {
                "type": "array",
                "items": {"type": "string"},
                "description": "参与对戏的角色名列表",
            },
            "character_ids": {
                "type": "array",
                "items": {"type": "string"},
                "description": "参与对戏的角色ID列表（与character_names二选一或互补）",
            },
            "scene": {"type": "string", "description": "场景描述——正在发生什么"},
            "turns": {"type": "integer", "description": "对戏回合数，默认2，最大4"},
            "outline_node_id": {"type": "string", "description": "关联的大纲节点ID，可选"},
        },
        required=["scene"],
        tool_type="generator",
        estimated_cost="medium",
        handler_name="dialogue_battle",
    ),
    ToolDef(
        name="start_novel_creation_session",
        description="Start the canonical structured novel-creation session used by the conversational Agent.",
        input_schema={
            "mode": {"type": "string", "description": "internal_llm|external_agent"},
            "user_brief": {"type": "string", "description": "User's novel brief"},
            "target_audience": {"type": "string", "description": "Target audience"},
            "genre": {"type": "string", "description": "Novel genre"},
            "platform": {"type": "string", "description": "Publishing platform"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="start_novel_creation_session",
    ),
    ToolDef(
        name="get_creation_session",
        description="Read the bounded creation-session overview and artifact index. Detailed artifact and entity bodies are intentionally omitted.",
        input_schema={"session_id": {"type": "string", "description": "Creation session ID"}},
        required=["session_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_session",
    ),
    ToolDef(
        name="get_creation_snapshot",
        description="Read a bounded immutable index containing revision, workflow states, locks/counts, and data shapes. Use exact artifact/entity reads for facts; stage bodies are intentionally omitted.",
        input_schema={"session_id": {"type": "string", "description": "Creation session ID"}},
        required=["session_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_snapshot",
    ),
    ToolDef(
        name="get_creation_operation",
        description="Read one durable creation Operation by operation ID or stage run ID, including progress and events.",
        input_schema={
            "operation_id": {"type": "string", "description": "Operation ID"},
            "run_id": {"type": "string", "description": "Creation stage run ID when operation_id is unknown"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_operation",
    ),
    ToolDef(
        name="patch_creation_session",
        description="Atomically patch session-level form, interview, model, or selected-concept fields with revision protection.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "changes": {"type": "object", "description": "Validated session-level fields to update"},
        },
        required=["session_id", "expected_revision", "changes"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="patch_creation_session_tool",
    ),
    ToolDef(
        name="get_creation_artifact",
        description="Read one structured creation artifact with status, provenance, locks, and active operation.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Creation artifact identifier"},
        },
        required=["session_id", "artifact"],
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_artifact",
    ),
    ToolDef(
        name="list_creation_artifacts",
        description="List bounded metadata and data shapes for every artifact; does not return stage bodies.",
        input_schema={"session_id": {"type": "string", "description": "Creation session ID"}},
        required=["session_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="list_creation_artifacts_tool",
    ),
    ToolDef(
        name="get_creation_dependencies",
        description="Inspect blockers and downstream artifacts that may become stale when one artifact changes.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Creation artifact identifier"},
        },
        required=["session_id", "artifact"],
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_dependencies",
    ),
    ToolDef(
        name="get_creation_dependency_graph",
        description="Read the complete artifact and entity dependency graph for a creation session.",
        input_schema={"session_id": {"type": "string", "description": "Creation session ID"}},
        required=["session_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_dependency_graph_tool",
    ),
    ToolDef(
        name="validate_creation_consistency",
        description="Run deterministic referential and stale-data checks without changing the creation draft.",
        input_schema={"session_id": {"type": "string", "description": "Creation session ID"}},
        required=["session_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="validate_creation_consistency_tool",
    ),
    ToolDef(
        name="patch_creation_artifact",
        description="Atomically apply lock-aware JSON Pointer changes to one creation artifact and return an impact summary.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Creation artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "changes": {"type": "array", "description": "Validated set|replace|append|remove|resize operations"},
        },
        required=["session_id", "artifact", "expected_revision", "changes"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="patch_creation_artifact_tool",
    ),
    ToolDef(
        name="lock_creation_fields",
        description="Lock JSON Pointer paths in one creation artifact so later assistant patches cannot modify them.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Creation artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "paths": {"type": "array", "description": "JSON Pointer paths to lock"},
        },
        required=["session_id", "artifact", "expected_revision", "paths"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="lock_creation_fields",
    ),
    ToolDef(
        name="unlock_creation_fields",
        description="Remove selected JSON Pointer locks from one creation artifact.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Creation artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "paths": {"type": "array", "description": "JSON Pointer paths to unlock"},
        },
        required=["session_id", "artifact", "expected_revision", "paths"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="unlock_creation_fields",
    ),
    ToolDef(
        name="undo_creation_artifact",
        description="Undo the most recent saved change to one creation artifact using its durable checkpoint.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Creation artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
        },
        required=["session_id", "artifact", "expected_revision"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="undo_creation_artifact_tool",
    ),
    ToolDef(
        name="list_creation_entities",
        description="Search a fenced, paginated summary index of characters, relationships, locations, factions, volumes, chapters, and scenes. Fetch exact candidates by entity ID before writing.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Optional artifact filter"},
            "entity_type": {"type": "string", "description": "Optional entity type filter"},
            "include_deleted": {"type": "boolean", "description": "Include soft-deleted entities"},
            "query": {"type": "string", "description": "Model-chosen name, relation, or fact query"},
            "offset": {"type": "integer", "description": "Zero-based result offset"},
            "limit": {"type": "integer", "description": "Page size, 1 to 50; default 20"},
        },
        required=["session_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="list_creation_entities_tool",
    ),
    ToolDef(
        name="get_creation_entity",
        description="Read one objectized creation entity with provenance and revision metadata.",
        input_schema={"entity_id": {"type": "string", "description": "Creation entity ID"}},
        required=["entity_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_entity_tool",
    ),
    ToolDef(
        name="patch_creation_entity",
        description="Atomically patch one creation entity while preserving the rest of its artifact and marking dependents stale.",
        input_schema={
            "entity_id": {"type": "string", "description": "Creation entity ID"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "changes": {"type": "array", "description": "Entity-relative JSON Pointer patch operations"},
        },
        required=["entity_id", "expected_revision", "changes"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="patch_creation_entity_tool",
    ),
    ToolDef(
        name="delete_creation_entity",
        description="Soft-delete one creation entity and valid dependent relations; version history remains restorable.",
        input_schema={
            "entity_id": {"type": "string", "description": "Creation entity ID"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
        },
        required=["entity_id", "expected_revision"],
        tool_type="write",
        writes_project_data=False,
        risk_level="medium",
        estimated_cost="free",
        handler_name="delete_creation_entity_tool",
    ),
    ToolDef(
        name="list_creation_artifact_versions",
        description="List the complete immutable history for one creation artifact.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Creation artifact identifier"},
            "limit": {"type": "integer", "description": "Maximum versions, default 100"},
        },
        required=["session_id", "artifact"],
        tool_type="read",
        estimated_cost="free",
        handler_name="list_creation_artifact_versions_tool",
    ),
    ToolDef(
        name="get_creation_artifact_diff",
        description="Compare one artifact version with its parent or another version using deterministic JSON Pointer changes.",
        input_schema={
            "version_id": {"type": "string", "description": "Artifact version ID"},
            "against_version_id": {"type": "string", "description": "Optional comparison version ID"},
        },
        required=["version_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="get_creation_artifact_diff_tool",
    ),
    ToolDef(
        name="restore_creation_artifact_version",
        description="Restore a validated historical artifact snapshot without deleting newer history.",
        input_schema={
            "version_id": {"type": "string", "description": "Artifact version ID"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
        },
        required=["version_id", "expected_revision"],
        tool_type="write",
        writes_project_data=False,
        risk_level="medium",
        estimated_cost="free",
        handler_name="restore_creation_artifact_version_tool",
    ),
    ToolDef(
        name="confirm_creation_artifact",
        description=(
            "Confirm the current artifact only when the latest user message explicitly approves "
            "that current revision. Never confirm content generated or modified in the same turn. "
            "This operation never generates the current or next artifact."
        ),
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
        },
        required=["session_id", "artifact", "expected_revision"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="confirm_creation_artifact",
    ),
    ToolDef(
        name="generate_creation_artifact",
        description=(
            "Generate one artifact or one new entity inside an artifact as a durable "
            "revision-protected run. When model is omitted, use the active default model."
        ),
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "model": {
                "type": "string",
                "description": "Optional model identity; omitted uses the active default model",
            },
            "use_model": {
                "type": "boolean",
                "description": "Use model generation when a model is available",
            },
            "entity_type": {"type": "string", "description": "Optional entity type for isolated new-entity generation"},
            "instruction": {"type": "string", "description": "Optional generation direction"},
            "context_entity_ids": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Exact entity IDs selected after retrieval; only these detailed records are supplied as generation evidence",
            },
            "context_artifacts": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Explicitly selected upstream artifacts; collection bodies remain summarized unless entity IDs are pinned",
            },
        },
        required=["session_id", "artifact", "expected_revision"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="model_or_free",
        handler_name="generate_creation_artifact",
    ),
    ToolDef(
        name="refine_creation_artifact",
        description=(
            "Refine only the requested artifact or entity while preserving locks and "
            "unrelated structured data. When model is omitted, use the active default model."
        ),
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "instruction": {"type": "string", "description": "Required localized refinement instruction"},
            "model": {
                "type": "string",
                "description": "Optional model identity; omitted uses the active default model",
            },
            "use_model": {
                "type": "boolean",
                "description": "Use model generation when a model is available",
            },
            "entity_id": {"type": "string", "description": "Optional existing entity ID for isolated refinement"},
            "context_entity_ids": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Exact supporting entity IDs selected after retrieval",
            },
            "context_artifacts": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Explicitly selected upstream artifacts",
            },
        },
        required=["session_id", "artifact", "expected_revision", "instruction"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="model_or_free",
        handler_name="refine_creation_artifact",
    ),
    ToolDef(
        name="regenerate_creation_artifact",
        description=(
            "Regenerate only the selected artifact or entity using a new durable run "
            "and a new idempotency context. When model is omitted, use the active default model."
        ),
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "artifact": {"type": "string", "description": "Artifact identifier"},
            "expected_revision": {"type": "integer", "description": "Required current session revision"},
            "instruction": {"type": "string", "description": "Optional replacement direction"},
            "model": {
                "type": "string",
                "description": "Optional model identity; omitted uses the active default model",
            },
            "use_model": {
                "type": "boolean",
                "description": "Use model generation when a model is available",
            },
            "entity_id": {"type": "string", "description": "Optional existing entity ID for isolated regeneration"},
            "context_entity_ids": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Exact supporting entity IDs selected after retrieval",
            },
            "context_artifacts": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Explicitly selected upstream artifacts",
            },
        },
        required=["session_id", "artifact", "expected_revision"],
        tool_type="write",
        writes_project_data=False,
        risk_level="medium",
        estimated_cost="model_or_free",
        handler_name="regenerate_creation_artifact",
    ),
    *(
        ToolDef(
            name=name,
            description=description,
            input_schema={"operation_id": {"type": "string", "description": "Durable creation Operation ID"}},
            required=["operation_id"],
            tool_type="write",
            writes_project_data=False,
            risk_level="low",
            estimated_cost="free",
            handler_name=name,
        )
        for name, description in (
            ("cancel_creation_operation", "Cancel a running creation operation and prevent unfinished data from being written."),
            ("pause_creation_operation", "Pause a creation operation at its supported checkpoint."),
            ("resume_creation_operation", "Resume a paused creation operation from its retained checkpoint."),
            ("retry_creation_operation", "Retry the current failed unit of a creation operation without replaying completed units."),
        )
    ),
    ToolDef(
        name="validate_creation_session",
        description="Inspect dependency, stale-data, and referential consistency diagnostics.",
        input_schema={"session_id": {"type": "string", "description": "Creation session ID"}},
        required=["session_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="validate_creation_session",
    ),
    ToolDef(
        name="finalize_creation_session",
        description="Idempotently convert the current creation session into a formal Siming project.",
        input_schema={"session_id": {"type": "string", "description": "Creation session ID"}},
        required=["session_id"],
        tool_type="write",
        writes_project_data=True,
        risk_level="medium",
        estimated_cost="free",
        handler_name="finalize_creation_session",
    ),
    ToolDef(
        name="import_creation_material",
        description="Persist a txt/md/docx/json source file and start checkpointed extraction for a creation session.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "file_path": {"type": "string", "description": "Local source file path"},
            "model": {"type": "string", "description": "Optional model used for evidence-only extraction"},
            "source_message_id": {"type": "string", "description": "Optional originating assistant conversation message"},
        },
        required=["session_id", "file_path"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="model_or_free",
        handler_name="import_creation_material",
    ),
    ToolDef(
        name="preview_creation_import",
        description="Read durable import progress, extracted candidates, conflicts, and provenance before any creation data is written.",
        input_schema={
            "session_id": {"type": "string", "description": "Creation session ID"},
            "import_id": {"type": "string", "description": "Durable material import run ID"},
        },
        required=["session_id", "import_id"],
        tool_type="read",
        estimated_cost="free",
        handler_name="preview_creation_import",
    ),
    ToolDef(
        name="apply_creation_import",
        description="Atomically apply selected import candidates with revision, confirmation, and lock protection.",
        input_schema={
            "import_id": {"type": "string", "description": "Durable material import run ID"},
            "selected_artifacts": {"type": "array", "description": "world_style|characters|locations|macro_outline|opening_outline"},
            "strategy": {"type": "string", "description": "merge|overwrite_unconfirmed|skip_conflicts"},
            "expected_revision": {"type": "integer", "description": "Required current creation session revision"},
        },
        required=["import_id", "selected_artifacts", "expected_revision"],
        tool_type="write",
        writes_project_data=False,
        risk_level="low",
        estimated_cost="free",
        handler_name="apply_creation_import",
    ),
    ToolDef(
        name="list_imported_files",
        description="List all imported files in the working directory. Returns file names, paths, sizes, and modification times.",
        input_schema={},
        tool_type="read",
        estimated_cost="free",
        handler_name="list_imported_files",
    ),
    ToolDef(
        name="read_imported_file",
        description="Read the content of a specific imported file from the working directory.",
        input_schema={
            "filename": {
                "type": "string",
                "description": "Name of the file to read (from list_imported_files)",
            },
            "max_size": {
                "type": "integer",
                "description": "Max characters to read (default 50000)",
            },
        },
        required=["filename"],
        tool_type="read",
        estimated_cost="free",
        handler_name="read_imported_file",
    ),
)


__all__ = ["TOOL_DEFINITIONS"]
