"""Application port for character profiles and continuity review data."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol


class CharacterWorkspace(Protocol):
    def list_characters(self, project_id: str, query: str | None = None) -> Sequence[Any]: ...
    def create_character(self, **values: Any) -> Any: ...
    def relationship_network(self, project_id: str) -> tuple[Sequence[Any], Sequence[Any]]: ...
    def create_version(self, **values: Any) -> Any: ...
    def delete_relationships(self, project_id: str, character_id: str) -> None: ...
    def delete(self, value: Any) -> None: ...
    def versions(self, character_id: str) -> Sequence[Any]: ...
    def version(self, character_id: str, version_id: str) -> Any | None: ...
    def targets_exist(self, project_id: str, target_ids: set[str]) -> bool: ...
    def replace_relationships(
        self,
        project_id: str,
        character_id: str,
        relationships: Sequence[Any],
    ) -> None: ...
    def ensure_ai_config(self, character: Any) -> Any: ...
    def change_logs(
        self,
        project_id: str,
        *,
        chapter_id: str | None = None,
        character_id: str | None = None,
        confirmed: bool | None = None,
        limit: int = 200,
    ) -> Sequence[Any]: ...
    def change_log(self, project_id: str, log_id: str) -> Any | None: ...
    def character(self, character_id: str) -> Any | None: ...
    def pending_change_logs(
        self,
        project_id: str,
        *,
        chapter_id: str | None = None,
        character_id: str | None = None,
    ) -> Sequence[Any]: ...
    def serialize_change_logs(self, logs: Sequence[Any]) -> list[dict]: ...


__all__ = ["CharacterWorkspace"]
