"""Persistence port for resumable novel-creation sessions."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol


class NovelCreationSessionStore(Protocol):
    def session(self, session_id: str) -> Any | None: ...
    def sessions(self, *, include_completed: bool, limit: int = 30) -> Sequence[Any]: ...
    def delete(self, session: Any) -> None: ...
    def run(self, run_id: str) -> Any | None: ...
    def running_stage(self, session_id: str, stage: str) -> Any | None: ...
    def latest_stage_operation(self, session_id: str, stage: str) -> Any | None: ...


__all__ = ["NovelCreationSessionStore"]
