"""Persistence port for the local model center."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol


class LocalModelStore(Protocol):
    def catalog_models(self) -> Sequence[Any]: ...
    def runtime_installation(self, runtime_key: str) -> Any | None: ...
    def task_settings(self) -> Sequence[Any]: ...
    def installed_models(self) -> Sequence[Any]: ...
    def download_tasks(self, *, limit: int = 100) -> Sequence[Any]: ...
    def download_task(self, task_id: str) -> Any | None: ...
    def model(self, model_key: str) -> Any | None: ...
    def task_setting(self, task_type: str) -> Any | None: ...
    def create_task_setting(self, task_type: str, model_key: str) -> Any: ...
    def delete(self, value: Any) -> None: ...
    def adapters(self, project_id: str | None = None) -> Sequence[Any]: ...
    def adapter(self, adapter_id: str) -> Any | None: ...
    def selected_adapters(self, adapter_ids: Sequence[str], model_key: str) -> Sequence[Any]: ...
    def datasets(self, project_id: str | None = None) -> Sequence[Any]: ...
    def training_jobs(self, project_id: str | None = None) -> Sequence[Any]: ...
    def training_job(self, job_id: str) -> Any | None: ...


__all__ = ["LocalModelStore"]
