"""Persistence port used by the workspace assistant controller."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol


class AssistantWorkspace(Protocol):
    def resolve_characters(
        self,
        project_id: str,
        names: Sequence[str],
        outline_node_id: str | None,
        *,
        limit: int,
    ) -> list[Any]: ...
    def create_chapter(self, **values: Any) -> Any: ...
    def create_summary(self, **values: Any) -> Any: ...
    def create_snapshot(self, **values: Any) -> Any: ...
    def characters_by_names(self, project_id: str, names: set[str]) -> Sequence[Any]: ...
    def clear_chapter_characters(self, chapter_id: str) -> None: ...
    def link_chapter_character(self, **values: Any) -> Any: ...
    def conversation(self, project_id: str, conversation_id: str) -> Any | None: ...
    def create_conversation(self, **values: Any) -> Any: ...
    def create_message(self, **values: Any) -> Any: ...
    def conversation_messages(self, conversation_id: str) -> Sequence[Any]: ...
    def previous_assistant_messages(self, conversation_id: str) -> Sequence[Any]: ...
    def conversations_with_counts(
        self,
        project_id: str,
        scope: str,
    ) -> Sequence[tuple[Any, int]]: ...
    def delete(self, value: Any) -> None: ...
    def runs(
        self,
        project_id: str,
        conversation_id: str | None,
        *,
        limit: int,
    ) -> Sequence[Any]: ...
    def run(self, project_id: str, run_id: str) -> Any | None: ...
    def run_steps(self, run_id: str) -> Sequence[Any]: ...
    def chapter(self, project_id: str, chapter_id: str) -> Any | None: ...
    def memories(
        self,
        project_id: str,
        categories: Sequence[str],
        *,
        limit: int,
    ) -> Sequence[Any]: ...
    def related_memories(
        self,
        project_id: str,
        categories: Sequence[str],
        terms: Sequence[str],
        *,
        limit: int,
    ) -> Sequence[Any]: ...


__all__ = ["AssistantWorkspace"]
