"""Compatibility exports for the domain-owned SQLAlchemy models.

New code imports models from its module infrastructure package. Existing REST,
MCP, CLI, migration, and plugin integrations may keep importing this module.
"""

from __future__ import annotations

from app.database.schema_models import SchemaMetadata
from app.database.session import Base
from app.modules.assistant.infrastructure.models import (
    AssistantConversation,
    AssistantMemory,
    AssistantMessage,
    AssistantRun,
    AssistantRunStep,
    ChapterDraft,
    RagChunk,
    RagChunkEmbedding,
    RagDocument,
    RagLink,
    SystemAssistantConversation,
    SystemAssistantMessage,
)
from app.modules.context.infrastructure.models import (
    ContextManifest,
    ContextManifestItem,
    ContextRebuildJob,
    ContextRebuildProject,
    ModelContextProfile,
)
from app.modules.continuity.infrastructure.models import (
    CatalogingApplyLog,
    CatalogingCandidate,
    CatalogingChapterRun,
    CatalogingFact,
    CatalogingJob,
    CausalEdge,
    ChapterQualityMetric,
    ChapterSummary,
    CharacterChangeLog,
    CharacterNarrativeState,
    CharacterTimeline,
    Foreshadowing,
    NarrativeCheckpoint,
    NarrativeDebt,
    WorldbuildingTimeline,
    WorldbuildingVersion,
)
from app.modules.creation.infrastructure.models import (
    NovelCreationSession,
    NovelCreationStageEvent,
    NovelCreationStageRun,
)
from app.modules.integrations.infrastructure.models import (
    ExternalAgentGlobalSettings,
    ExternalAgentSettings,
    McpServerConfig,
    MethodCard,
    PublicPromptPack,
    Skill,
    SkillVersion,
    default_external_agent_enabled_packs,
    default_trusted_local_clients,
)
from app.modules.model_runtime.infrastructure.legacy_models import (
    LocalModel,
    LocalRuntimeInstallation,
    ModelAdapter,
    ModelDownloadTask,
    OpenCodeActivationJob,
    TrainingDataset,
    TrainingJob,
)
from app.modules.model_runtime.infrastructure.models import APIConfig, LocalModelTaskSetting
from app.modules.operations.infrastructure.legacy_models import (
    AgentPlan,
    AgentPlanStep,
    AgentRun,
    AgentRunEvent,
    ScheduledTask,
)
from app.modules.operations.infrastructure.models import OperationEvent, OperationRun
from app.modules.story.infrastructure.entities import (
    Chapter,
    ChapterCharacter,
    ChapterSnapshot,
    ChapterWorldbuilding,
    Character,
    CharacterAIConfig,
    CharacterAlias,
    CharacterRelationship,
    CharacterVersion,
    DeconstructionReport,
    OutlineNode,
    OutlineNodeCharacter,
    Project,
    WorldbuildingEntry,
    WorldbuildingRelation,
)
from app.modules.story.infrastructure.models import ContentSyncJob

__all__ = [
    "Project",
    "WorldbuildingEntry",
    "WorldbuildingRelation",
    "Character",
    "CharacterVersion",
    "CharacterAIConfig",
    "CharacterAlias",
    "CharacterRelationship",
    "OutlineNode",
    "OutlineNodeCharacter",
    "Chapter",
    "ChapterCharacter",
    "ChapterWorldbuilding",
    "ChapterSnapshot",
    "DeconstructionReport",
    "OpenCodeActivationJob",
    "LocalModel",
    "LocalRuntimeInstallation",
    "ModelDownloadTask",
    "ModelAdapter",
    "TrainingDataset",
    "TrainingJob",
    "AssistantConversation",
    "AssistantMessage",
    "SystemAssistantConversation",
    "SystemAssistantMessage",
    "AssistantRun",
    "AssistantRunStep",
    "AssistantMemory",
    "ChapterDraft",
    "RagDocument",
    "RagChunk",
    "RagLink",
    "RagChunkEmbedding",
    "ChapterSummary",
    "CharacterChangeLog",
    "CharacterTimeline",
    "WorldbuildingVersion",
    "WorldbuildingTimeline",
    "CatalogingJob",
    "CatalogingChapterRun",
    "CatalogingFact",
    "CatalogingCandidate",
    "CatalogingApplyLog",
    "Foreshadowing",
    "CausalEdge",
    "NarrativeDebt",
    "CharacterNarrativeState",
    "ChapterQualityMetric",
    "NarrativeCheckpoint",
    "NovelCreationSession",
    "NovelCreationStageRun",
    "NovelCreationStageEvent",
    "AgentPlan",
    "AgentPlanStep",
    "ScheduledTask",
    "AgentRun",
    "AgentRunEvent",
    "default_external_agent_enabled_packs",
    "default_trusted_local_clients",
    "Skill",
    "SkillVersion",
    "McpServerConfig",
    "ExternalAgentSettings",
    "PublicPromptPack",
    "MethodCard",
    "ExternalAgentGlobalSettings",
    "Base",
    "SchemaMetadata",
    "ContextManifest",
    "ContextManifestItem",
    "ContextRebuildJob",
    "ContextRebuildProject",
    "ModelContextProfile",
    "APIConfig",
    "LocalModelTaskSetting",
    "OperationEvent",
    "OperationRun",
    "ContentSyncJob",
]
