# ruff: noqa: E501
"""Story workspace tool declarations."""

from __future__ import annotations

from app.architecture.tool_definition import ToolDef

TOOL_DEFINITIONS: tuple[ToolDef, ...] = (
    ToolDef(
        name="list_projects",
        description="列出系统中的作品。可按标题或简介搜索。用于项目助手帮助用户管理多个作品；不会读取或修改API Key。",
        input_schema={
            "query": {"type": "string", "description": "可选，按作品标题或简介搜索"},
            "limit": {"type": "integer", "description": "返回数量上限，默认50"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="list_projects",
    ),
    ToolDef(
        name="get_project_info",
        description="读取作品设置与基础信息。默认读取当前作品，也可传入作品ID。不会读取API Key。",
        input_schema={
            "id": {"type": "string", "description": "可选，作品ID。不传则读取当前作品"},
            "project_id": {"type": "string", "description": "兼容字段，同id"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="get_project_info",
    ),
    ToolDef(
        name="get_project_files_info",
        description="读取作品的文件源目录信息。用于 Claude/Codex 了解章节、角色、大纲、世界观在本机项目目录中的位置。",
        input_schema={
            "project_id": {"type": "string", "description": "可选，作品ID。不传则使用当前作品"}
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="get_project_files_info",
    ),
    ToolDef(
        name="list_project_files",
        description="列出作品目录内的文件或子目录。只能访问该作品目录，不能读取 API Key 或系统设置。",
        input_schema={
            "project_id": {"type": "string", "description": "可选，作品ID。不传则使用当前作品"},
            "path": {
                "type": "string",
                "description": "相对作品目录的子目录，如 chapters、characters、outline",
            },
            "limit": {"type": "integer", "description": "返回数量上限，默认200"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="list_project_files",
    ),
    ToolDef(
        name="read_project_file",
        description="读取作品目录内的文本文件，如章节 Markdown、角色 JSON、世界观 JSON。大文件会按 max_chars 截断。",
        input_schema={
            "project_id": {"type": "string", "description": "可选，作品ID。不传则使用当前作品"},
            "path": {"type": "string", "description": "作品目录内的相对文件路径"},
            "max_chars": {"type": "integer", "description": "最多读取字符数，默认200000"},
        },
        required=["path"],
        tool_type="read",
        estimated_cost="free",
        handler_name="read_project_file",
    ),
    ToolDef(
        name="search_project_files",
        description="在作品目录内搜索文本。适合外部 Agent 快速定位章节正文、角色卡、大纲或世界观中的线索。",
        input_schema={
            "project_id": {"type": "string", "description": "可选，作品ID。不传则使用当前作品"},
            "query": {"type": "string", "description": "要搜索的文本"},
            "path": {"type": "string", "description": "可选，限定搜索子目录或文件"},
            "limit": {"type": "integer", "description": "匹配数量上限，默认50"},
            "context_chars": {
                "type": "integer",
                "description": "每个命中前后保留的字符数，默认120",
            },
        },
        required=["query"],
        tool_type="read",
        estimated_cost="free",
        handler_name="search_project_files",
    ),
    ToolDef(
        name="write_project_file",
        description="写入作品目录内的非规范文本文件。Siming 2.1 起数据库是唯一写入源，chapters/characters/worldbuilding/outline/relationships 目录只是只读镜像；如需创建或修改章节、角色、大纲、世界观、关系，必须使用对应 create/update/delete 工具。",
        input_schema={
            "project_id": {"type": "string", "description": "可选，作品ID。不传则使用当前作品"},
            "path": {
                "type": "string",
                "description": "作品目录内的相对文件路径；不能位于规范镜像目录",
            },
            "content": {"type": "string", "description": "要写入的完整文本内容"},
            "overwrite": {"type": "boolean", "description": "是否覆盖已有文件，默认true"},
        },
        required=["path", "content"],
        tool_type="write",
        writes_project_data=True,
        estimated_cost="free",
        handler_name="write_project_file",
    ),
    ToolDef(
        name="sync_project_files",
        description="手动同步作品文件目录。默认 db_to_files，将数据库权威数据刷新为文件镜像。files_to_db/import/both 是危险的修复导入路径，必须传 confirm_import_from_files=true 才会执行。",
        input_schema={
            "project_id": {"type": "string", "description": "可选，作品ID。不传则使用当前作品"},
            "direction": {
                "type": "string",
                "description": "db_to_files|files_to_db|import|export|both，默认 db_to_files",
            },
            "confirm_import_from_files": {
                "type": "boolean",
                "description": "仅在 files_to_db/import/both 时需要；确认允许文件镜像反向覆盖数据库",
            },
        },
        tool_type="write",
        writes_project_data=True,
        estimated_cost="free",
        handler_name="sync_project_files",
    ),
    ToolDef(
        name="create_project",
        description="创建新作品。可设置简介、标签、文风、禁用句式、修辞限制、每日字数目标等基础信息。不会创建或修改API Key。",
        input_schema={
            "title": {"type": "string", "description": "作品标题"},
            "description": {"type": "string", "description": "作品简介"},
            "tags": {"type": "array", "items": {"type": "string"}, "description": "作品标签"},
            "narrative_perspective": {
                "type": "string",
                "description": "叙事视角，如 third_person/first_person",
            },
            "writing_style": {"type": "string", "description": "文风偏好"},
            "forbidden_sentence_patterns": {"type": "string", "description": "禁用句式，每行一条"},
            "rhetoric_guidelines": {"type": "string", "description": "修辞和比喻使用限制"},
            "short_sentences": {"type": "boolean", "description": "是否启用短句模式"},
            "custom_style_prompt": {"type": "string", "description": "自定义风格提示词"},
            "daily_word_goal": {"type": "integer", "description": "每日字数目标"},
            "context_manifest_id": {
                "type": "string",
                "description": "Governed task manifest required for MCP formal writes",
            },
        },
        required=["title"],
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="create_project",
    ),
    ToolDef(
        name="update_project_info",
        description="更新当前或指定作品的基础设置。可修改标题、简介、文风、禁用句式等；不能修改API Key或模型密钥。",
        input_schema={
            "id": {"type": "string", "description": "可选，作品ID。不传则更新当前作品"},
            "project_id": {"type": "string", "description": "兼容字段，同id"},
            "title": {"type": "string", "description": "作品标题"},
            "description": {"type": "string", "description": "作品简介"},
            "tags": {"type": "array", "items": {"type": "string"}, "description": "作品标签"},
            "narrative_perspective": {"type": "string", "description": "叙事视角"},
            "writing_style": {"type": "string", "description": "文风偏好"},
            "forbidden_sentence_patterns": {"type": "string", "description": "禁用句式，每行一条"},
            "rhetoric_guidelines": {"type": "string", "description": "修辞和比喻限制"},
            "short_sentences": {"type": "boolean", "description": "是否启用短句模式"},
            "custom_style_prompt": {"type": "string", "description": "自定义风格提示词"},
            "daily_word_goal": {"type": "integer", "description": "每日字数目标"},
        },
        tool_type="write",
        estimated_cost="free",
        handler_name="update_project_info",
    ),
    ToolDef(
        name="delete_project",
        description="删除作品及其全部关联数据。危险操作，必须在用户明确确认删除指定作品后才能调用。",
        input_schema={
            "id": {"type": "string", "description": "要删除的作品ID"},
            "project_id": {"type": "string", "description": "兼容字段，同id"},
        },
        tool_type="write",
        requires_confirmation=True,
        estimated_cost="free",
        handler_name="delete_project",
    ),
    ToolDef(
        name="export_project",
        description="导出当前作品内容，生成 txt/docx/pdf 文件。可导出章节、大纲、角色、世界观或全部内容。",
        input_schema={
            "scope": {
                "type": "string",
                "description": "导出范围：chapters|outline|characters|worldbuilding|all|single|selected，默认all",
            },
            "format": {"type": "string", "description": "导出格式：txt|docx|pdf，默认txt"},
            "chapter_ids": {
                "type": "array",
                "items": {"type": "string"},
                "description": "scope=selected/single时要导出的章节ID列表",
            },
            "include_outline": {"type": "boolean", "description": "导出章节时是否附带大纲"},
            "include_characters": {"type": "boolean", "description": "导出章节时是否附带角色档案"},
            "include_worldbuilding": {"type": "boolean", "description": "导出章节时是否附带世界观"},
        },
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="export_project",
    ),
    ToolDef(
        name="get_export_word_count",
        description="统计当前作品章节总字数和每章字数，用于导出前检查或写作进度统计。",
        input_schema={},
        tool_type="read",
        estimated_cost="free",
        handler_name="get_export_word_count",
    ),
    ToolDef(
        name="preview_import_splits",
        description="Preview chapter split suggestions for pasted novel text before importing it as chapters.",
        input_schema={
            "text": {"type": "string", "description": "Full text to split into chapters"},
            "model": {
                "type": "string",
                "description": "Optional model override for LLM split correction",
            },
        },
        required=["text"],
        tool_type="analysis",
        estimated_cost="low",
        handler_name="preview_import_splits",
    ),
    ToolDef(
        name="import_text_as_chapters",
        description="Import pasted text as project chapters. Can use provided split suggestions or auto-split first.",
        input_schema={
            "text": {"type": "string", "description": "Full text to import"},
            "splits": {
                "type": "array",
                "items": {"type": "object"},
                "description": "Optional split suggestions from preview_import_splits",
            },
            "outline_node_id": {
                "type": "string",
                "description": "Optional outline node ID to link imported chapters",
            },
            "auto_split": {
                "type": "boolean",
                "description": "Auto-detect chapter boundaries when splits are omitted; default true",
            },
            "model": {
                "type": "string",
                "description": "Optional model override for split correction",
            },
        },
        required=["text"],
        tool_type="write",
        idempotent=True,
        estimated_cost="low",
        handler_name="import_text_as_chapters",
    ),
    ToolDef(
        name="import_file_as_chapters",
        description="Import a local TXT/DOCX file from file_path into an existing project as chapters. Prefer this over passing a whole novel as text through MCP.",
        input_schema={
            "file_path": {
                "type": "string",
                "description": "Local .txt or .docx path on the same machine as Siming",
            },
            "splits": {
                "type": "array",
                "items": {"type": "object"},
                "description": "Optional split suggestions from preview_import_splits",
            },
            "outline_node_id": {
                "type": "string",
                "description": "Optional outline node ID to link imported chapters",
            },
            "auto_split": {
                "type": "boolean",
                "description": "Auto-detect chapter boundaries when splits are omitted; default true",
            },
            "model": {
                "type": "string",
                "description": "Optional model override for split correction",
            },
        },
        required=["file_path"],
        tool_type="write",
        idempotent=True,
        estimated_cost="low",
        handler_name="import_file_as_chapters",
    ),
    ToolDef(
        name="import_file_as_project",
        description="Create a new project from a local TXT/DOCX file and import the file as chapters in one step. Best tool for requests like '导入这本小说为新作品'.",
        input_schema={
            "file_path": {
                "type": "string",
                "description": "Local .txt or .docx path on the same machine as Siming",
            },
            "title": {
                "type": "string",
                "description": "Project title; defaults to the file name without extension",
            },
            "description": {"type": "string", "description": "Project description"},
            "tags": {"type": "array", "items": {"type": "string"}, "description": "Project tags"},
            "narrative_perspective": {
                "type": "string",
                "description": "Narrative perspective, e.g. third_person/first_person",
            },
            "writing_style": {"type": "string", "description": "Writing style preference"},
            "forbidden_sentence_patterns": {
                "type": "string",
                "description": "Forbidden sentence patterns, one per line",
            },
            "rhetoric_guidelines": {
                "type": "string",
                "description": "Rhetoric and metaphor guidelines",
            },
            "short_sentences": {"type": "boolean", "description": "Enable short sentence mode"},
            "custom_style_prompt": {"type": "string", "description": "Custom style prompt"},
            "daily_word_goal": {"type": "integer", "description": "Daily word goal"},
            "auto_split": {
                "type": "boolean",
                "description": "Auto-detect chapter boundaries; default true",
            },
            "model": {
                "type": "string",
                "description": "Optional model override for split correction",
            },
        },
        required=["file_path"],
        tool_type="write",
        idempotent=True,
        estimated_cost="low",
        handler_name="import_file_as_project",
    ),
    ToolDef(
        name="get_today_writing_stats",
        description="Read today's writing statistics for the current project.",
        input_schema={},
        tool_type="read",
        estimated_cost="free",
        handler_name="get_today_writing_stats",
    ),
    ToolDef(
        name="get_writing_stats_history",
        description="Read daily writing statistics history for the current project.",
        input_schema={
            "days": {"type": "integer", "description": "Number of days, 1-365; default 7"}
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="get_writing_stats_history",
    ),
    ToolDef(
        name="set_daily_word_goal",
        description="Set the current project's daily word-count goal.",
        input_schema={
            "daily_word_goal": {"type": "integer", "description": "Daily target word count"}
        },
        required=["daily_word_goal"],
        tool_type="write",
        estimated_cost="free",
        handler_name="set_daily_word_goal",
    ),
    ToolDef(
        name="list_duplicate_characters",
        description="Find likely duplicate character cards for manual review or merge.",
        input_schema={
            "limit": {
                "type": "integer",
                "description": "Maximum duplicate pairs to return; default 80",
            }
        },
        tool_type="analysis",
        estimated_cost="free",
        handler_name="list_duplicate_characters",
    ),
    ToolDef(
        name="preview_character_merge",
        description="Preview how two duplicate character cards would be merged.",
        input_schema={
            "primary_id": {"type": "string", "description": "Character ID to keep"},
            "secondary_id": {"type": "string", "description": "Character ID to merge into primary"},
            "canonical_name": {"type": "string", "description": "Optional final canonical name"},
        },
        required=["primary_id", "secondary_id"],
        tool_type="analysis",
        estimated_cost="free",
        handler_name="preview_character_merge",
    ),
    ToolDef(
        name="merge_duplicate_characters",
        description="Merge a duplicate character into the primary character card. Requires clear user confirmation.",
        input_schema={
            "primary_id": {"type": "string", "description": "Character ID to keep"},
            "secondary_id": {"type": "string", "description": "Character ID to merge into primary"},
            "canonical_name": {"type": "string", "description": "Optional final canonical name"},
            "reason": {
                "type": "string",
                "description": "Why these two cards are the same character",
            },
        },
        required=["primary_id", "secondary_id"],
        tool_type="write",
        requires_confirmation=True,
        estimated_cost="free",
        handler_name="merge_duplicate_characters",
    ),
    ToolDef(
        name="search_characters",
        description="按角色名片段搜索角色完整档案。返回角色姓名、外貌、性格、背景、能力列表、角色类型。内容截断至8000字。",
        input_schema={
            "query": {"type": "string", "description": "角色名片段，支持模糊匹配"},
            "limit": {"type": "integer", "description": "返回条数上限，默认10，最大30"},
        },
        required=["query"],
        tool_type="read",
        estimated_cost="free",
        handler_name="search_characters",
    ),
    ToolDef(
        name="search_chapters",
        description="搜索章节全文。按标题搜索，可选限定大纲节点。正文截断至8000字。",
        input_schema={
            "query": {"type": "string", "description": "章节标题片段，支持模糊匹配"},
            "outline_node_id": {
                "type": "string",
                "description": "限定大纲节点ID，传入后忽略query直接返回该节点下所有章节",
            },
            "limit": {"type": "integer", "description": "返回条数上限，默认5，最大20"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="search_chapters",
    ),
    ToolDef(
        name="search_outline",
        description="按标题搜索大纲节点，或查看指定节点的子树。",
        input_schema={
            "query": {"type": "string", "description": "大纲标题片段，支持模糊匹配"},
            "node_id": {
                "type": "string",
                "description": "指定节点ID，传入后返回该节点及所有子孙节点（忽略query）",
            },
            "limit": {"type": "integer", "description": "返回条数上限，默认10，最大60"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="search_outline",
    ),
    ToolDef(
        name="search_outline_tree",
        description="获取完整大纲树结构（仅标题和层级），或指定子树。",
        input_schema={
            "root_id": {"type": "string", "description": "可选，子树根节点ID。不传则返回完整大纲树"}
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="search_outline_tree",
    ),
    ToolDef(
        name="search_worldbuilding",
        description="按标题搜索世界观条目完整内容。可按维度过滤。",
        input_schema={
            "query": {"type": "string", "description": "设定标题片段，支持模糊匹配"},
            "dimension": {
                "type": "string",
                "description": "限定维度：geography|history|factions|power_system|races|culture",
            },
            "limit": {"type": "integer", "description": "返回条数上限，默认10，最大30"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="search_worldbuilding",
    ),
    ToolDef(
        name="search_relationships",
        description="查询角色的所有关系（与谁有关系、方向、关系类型、描述）。",
        input_schema={
            "character_id": {"type": "string", "description": "角色ID，优先使用"},
            "character_name": {"type": "string", "description": "角色名，character_id为空时使用"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="search_relationships",
    ),
    ToolDef(
        name="list_characters",
        description="快速概览全部角色（仅返回姓名、ID、角色类型）。轻量级，先调此工具确认角色是否存在，再决定是否需要 search_characters 查详情。",
        input_schema={},
        tool_type="read",
        estimated_cost="free",
        handler_name="list_characters",
    ),
    ToolDef(
        name="list_chapters",
        description="快速概览全部章节（仅返回标题、ID、对应大纲节点ID）。轻量级，不含正文。",
        input_schema={},
        tool_type="read",
        estimated_cost="free",
        handler_name="list_chapters",
    ),
    ToolDef(
        name="list_worldbuilding",
        description="快速概览全部世界观条目（仅返回标题、ID、维度）。轻量级，不含正文。",
        input_schema={},
        tool_type="read",
        estimated_cost="free",
        handler_name="list_worldbuilding",
    ),
    ToolDef(
        name="create_worldbuilding_entry",
        description="创建一条新的世界观设定条目。",
        input_schema={
            "title": {"type": "string", "description": "条目标题"},
            "content": {"type": "string", "description": "条目正文内容"},
            "dimension": {
                "type": "string",
                "description": "所属维度：geography|history|factions|power_system|races|culture，默认culture",
            },
            "sort_order": {"type": "integer", "description": "排序序号"},
            "related_characters": {
                "type": "array",
                "items": {"type": "string"},
                "description": "关联角色名列表",
            },
            "plot_usage": {"type": "string", "description": "剧情用途说明"},
            "constraints": {
                "type": "array",
                "items": {"type": "string"},
                "description": "设定约束列表",
            },
            "status": {
                "type": "string",
                "description": "条目状态：active|archived|draft，默认active",
            },
            "confidence": {"type": "number", "description": "置信度评分，0-1"},
            "first_seen_chapter_id": {"type": "string", "description": "首次出现的章节ID"},
            "last_updated_chapter_id": {"type": "string", "description": "最后更新的章节ID"},
        },
        required=["title", "content"],
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="create_worldbuilding_entry",
    ),
    ToolDef(
        name="update_worldbuilding_entry",
        description="更新一条世界观条目。用ID或标题定位。",
        input_schema={
            "id": {"type": "string", "description": "条目ID（优先使用）"},
            "title": {
                "type": "string",
                "description": "条目标题（id为空时用于定位；也可用于重命名）",
            },
            "dimension": {"type": "string", "description": "更新维度"},
            "content": {"type": "string", "description": "更新正文"},
            "sort_order": {"type": "integer", "description": "更新排序"},
            "status": {"type": "string", "description": "更新状态：active|archived|draft"},
            "confidence": {"type": "number", "description": "更新置信度"},
            "first_seen_chapter_id": {"type": "string", "description": "更新首次出现章节ID"},
            "last_updated_chapter_id": {"type": "string", "description": "更新最后更新章节ID"},
        },
        required=["id"],
        tool_type="write",
        estimated_cost="free",
        handler_name="update_worldbuilding_entry",
    ),
    ToolDef(
        name="delete_worldbuilding_entry",
        description="删除一条世界观条目。用ID或标题定位。",
        input_schema={
            "id": {"type": "string", "description": "条目ID（优先使用）"},
            "title": {"type": "string", "description": "条目标题（id为空时使用）"},
        },
        tool_type="write",
        requires_confirmation=True,
        estimated_cost="free",
        handler_name="delete_worldbuilding_entry",
    ),
    ToolDef(
        name="create_outline_node",
        description="创建新的大纲节点。",
        input_schema={
            "title": {"type": "string", "description": "节点标题"},
            "parent_id": {"type": "string", "description": "父节点ID，可空（作为根节点）"},
            "node_type": {
                "type": "string",
                "description": "节点类型：volume|chapter|section，默认chapter",
            },
            "summary": {"type": "string", "description": "本节点剧情摘要"},
            "status": {
                "type": "string",
                "description": "状态：pending|in_progress|completed，默认pending",
            },
            "character_names": {
                "type": "array",
                "items": {"type": "string"},
                "description": "本节点涉及的角色名列表",
            },
            "source_chapter_id": {"type": "string", "description": "关联的源章节ID"},
            "actual_summary": {"type": "string", "description": "实际完成后的摘要"},
            "planned_summary": {"type": "string", "description": "计划中的摘要"},
            "cataloging_status": {"type": "string", "description": "编目状态"},
            "metadata": {
                "type": "object",
                "description": "section 场景元数据：scene_number/purpose/location/timeline/pov_character/characters/entry_state/exit_state/emotional_residue/unresolved_actions",
            },
        },
        required=["title"],
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="create_outline_node",
    ),
    ToolDef(
        name="create_outline_nodes",
        description="批量创建新的大纲节点。通常用于保存 outline_writer 生成的一组节点。",
        input_schema={
            "nodes": {
                "type": "array",
                "items": {"type": "object"},
                "description": "大纲节点列表，每个节点可包含 title/node_type/summary/status/character_names/parent_id",
            },
            "parent_id": {"type": "string", "description": "可选，批量节点的默认父节点ID"},
        },
        required=["nodes"],
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="create_outline_nodes",
    ),
    ToolDef(
        name="update_outline_node",
        description="更新大纲节点。用ID或标题定位。",
        input_schema={
            "id": {
                "type": "string",
                "description": "节点ID（优先使用）。也可用 title/outline_node_id/node_id/outline_node_title/current_title/old_title 定位",
            },
            "title": {"type": "string", "description": "更新标题"},
            "summary": {"type": "string", "description": "更新摘要"},
            "status": {"type": "string", "description": "更新状态：pending|in_progress|completed"},
            "node_type": {"type": "string", "description": "更新节点类型：volume|chapter|section"},
            "character_names": {
                "type": "array",
                "items": {"type": "string"},
                "description": "更新涉及的角色名列表（替换全部已有关联）",
            },
            "source_chapter_id": {"type": "string", "description": "更新关联的源章节ID"},
            "actual_summary": {"type": "string", "description": "更新实际完成后的摘要"},
            "planned_summary": {"type": "string", "description": "更新计划中的摘要"},
            "cataloging_status": {"type": "string", "description": "更新编目状态"},
            "metadata": {"type": "object", "description": "更新 section 场景元数据"},
        },
        tool_type="write",
        estimated_cost="free",
        handler_name="update_outline_node",
    ),
    ToolDef(
        name="delete_outline_node",
        description="删除大纲节点（级联删除所有子节点）。用ID或标题定位。",
        input_schema={
            "id": {
                "type": "string",
                "description": "节点ID（优先使用）。也可用 node_id/outline_node_id/title 定位",
            }
        },
        tool_type="write",
        requires_confirmation=True,
        estimated_cost="free",
        handler_name="delete_outline_node",
    ),
    ToolDef(
        name="create_character",
        description="创建新角色，含完整人物卡片。",
        input_schema={
            "name": {"type": "string", "description": "角色名（必填，最长100字）"},
            "appearance": {"type": "string", "description": "外貌描写"},
            "personality": {"type": "string", "description": "性格特征"},
            "background": {"type": "string", "description": "背景故事"},
            "abilities": {
                "type": "array",
                "items": {"type": "string"},
                "description": "能力/技能列表",
            },
            "role_type": {
                "type": "string",
                "description": "角色类型：protagonist|supporting|antagonist|mentor|other，默认supporting",
            },
            "age": {
                "type": "string",
                "description": "年龄/时间状态，如 3岁、约16岁、外表16岁实际200岁、成年",
            },
            "speech_style": {"type": "string", "description": "说话风格，可合并进背景/AI提示词"},
            "motivation": {"type": "string", "description": "当前动机，可合并进背景/AI提示词"},
            "conflict": {"type": "string", "description": "核心冲突，可合并进背景/AI提示词"},
            "ai_config": {
                "type": "object",
                "description": "角色AI扮演配置，含 tone_style/catchphrases/verbosity/emotion_tendency/custom_system_prompt",
            },
            "custom_system_prompt": {
                "type": "string",
                "description": "角色AI扮演提示词，可直接存入角色AI配置",
            },
            "life_status": {"type": "string", "description": "生死状态，如 存活/死亡/失踪/重伤"},
            "current_location": {"type": "string", "description": "当前位置"},
            "realm_or_level": {"type": "string", "description": "境界/等级/修为"},
            "physical_state": {"type": "string", "description": "身体状况"},
            "mental_state": {"type": "string", "description": "心理状态"},
            "current_goal": {"type": "string", "description": "当前目标"},
            "active_conflict": {"type": "string", "description": "当前冲突/困境"},
            "abilities_state": {
                "type": "string",
                "description": "能力当前状态（如封印中、受伤无法使用等）",
            },
            "items_or_assets": {"type": "string", "description": "持有物/资源"},
            "profile": {
                "type": "object",
                "description": "稳定写作锁：core_motivation/inner_lack/core_belief/public_persona/hidden_persona/reveal_chapter/moral_taboo/voice/action_habit/trauma_trigger",
            },
        },
        required=["name"],
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="create_character",
    ),
    ToolDef(
        name="update_character",
        description="更新角色信息。用ID或角色名定位。只有传入的字段才会被更新。appearance、age 和所有 current_state 字段是逐章覆盖的当前状态，不是追加。",
        input_schema={
            "id": {"type": "string", "description": "角色ID（优先使用）"},
            "name": {"type": "string", "description": "角色名（id为空时用于定位）"},
            "personality": {"type": "string", "description": "更新性格（覆盖）"},
            "background": {
                "type": "string",
                "description": "更新背景（必须是重写合并后的完整版本，不是追加片段）",
            },
            "abilities": {
                "type": "array",
                "items": {"type": "string"},
                "description": "更新能力列表（替换全部）",
            },
            "role_type": {
                "type": "string",
                "description": "更新角色类型：protagonist|supporting|antagonist|mentor|other",
            },
            "ai_config": {
                "type": "object",
                "description": "更新角色AI扮演配置，含 tone_style/catchphrases/verbosity/emotion_tendency/custom_system_prompt",
            },
            "custom_system_prompt": {
                "type": "string",
                "description": "更新角色AI扮演提示词（必须是完整版本）",
            },
            "appearance": {
                "type": "string",
                "description": "当前外貌（逐章覆盖，如受伤/换装/成长等变化）",
            },
            "age": {
                "type": "string",
                "description": "当前年龄/时间状态，如 3岁、约16岁、外表16岁实际200岁",
            },
            "life_status": {"type": "string", "description": "生死状态，如 存活/死亡/失踪/重伤"},
            "current_location": {"type": "string", "description": "当前位置"},
            "realm_or_level": {"type": "string", "description": "境界/等级/修为"},
            "physical_state": {"type": "string", "description": "身体状况"},
            "mental_state": {"type": "string", "description": "心理状态"},
            "current_goal": {"type": "string", "description": "当前目标"},
            "active_conflict": {"type": "string", "description": "当前冲突/困境"},
            "abilities_state": {
                "type": "string",
                "description": "能力当前状态（如封印中、受伤无法使用等）",
            },
            "items_or_assets": {"type": "string", "description": "持有物/资源"},
            "profile": {"type": "object", "description": "更新稳定写作锁；提交完整 profile 对象"},
        },
        tool_type="write",
        estimated_cost="free",
        handler_name="update_character",
    ),
    ToolDef(
        name="delete_character",
        description="删除角色。用ID或角色名定位。",
        input_schema={
            "id": {"type": "string", "description": "角色ID（优先使用）"},
            "name": {"type": "string", "description": "角色名（id为空时使用）"},
        },
        tool_type="write",
        requires_confirmation=True,
        estimated_cost="free",
        handler_name="delete_character",
    ),
    ToolDef(
        name="create_relationship",
        description="在两个角色之间创建关系。",
        input_schema={
            "source": {"type": "string", "description": "角色A的名字或ID（也可用 from 字段）"},
            "target": {"type": "string", "description": "角色B的名字或ID（也可用 to 字段）"},
            "relationship_type": {
                "type": "string",
                "description": "关系类型，如 父子/师徒/恋人/仇敌，默认'关联'",
            },
            "description": {"type": "string", "description": "关系描述"},
        },
        required=["source", "target"],
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="create_relationship",
    ),
    ToolDef(
        name="update_relationship",
        description="更新两个角色之间的关系类型或描述。用source+target定位。",
        input_schema={
            "source": {"type": "string", "description": "角色A的名字或ID（必填，也可用 from）"},
            "target": {"type": "string", "description": "角色B的名字或ID（必填，也可用 to）"},
            "relationship_type": {"type": "string", "description": "更新关系类型"},
            "description": {"type": "string", "description": "更新关系描述"},
        },
        required=["source", "target"],
        tool_type="write",
        estimated_cost="free",
        handler_name="update_relationship",
    ),
    ToolDef(
        name="delete_relationship",
        description="删除两个角色之间的关系。用source+target定位。",
        input_schema={
            "source": {"type": "string", "description": "角色A的名字或ID（必填，也可用 from）"},
            "target": {"type": "string", "description": "角色B的名字或ID（必填，也可用 to）"},
        },
        required=["source", "target"],
        tool_type="write",
        requires_confirmation=True,
        estimated_cost="free",
        handler_name="delete_relationship",
    ),
    ToolDef(
        name="create_chapter",
        description="创建新章节。正文将自动修复禁用句式。创建前须已有对应大纲节点。若正文来自chapter_writer，优先传draft_id/content_ref，避免复制长正文导致截断。",
        input_schema={
            "title": {"type": "string", "description": "章节标题"},
            "content": {
                "type": "string",
                "description": "章节正文，1800-2500字。内部换行用\\n。对白可自由使用引号。",
            },
            "draft_id": {
                "type": "string",
                "description": "chapter_writer返回的草稿ID。优先使用它保存完整正文，避免长正文在工具参数中截断。",
            },
            "content_ref": {
                "type": "string",
                "description": "同draft_id，chapter_writer返回的正文引用。",
            },
            "skip_style_repair": {
                "type": "boolean",
                "description": "是否跳过保存时禁用句式自动修复，默认false。",
            },
            "outline_node_id": {
                "type": "string",
                "description": "对应的大纲节点ID（优先）。也可用 outline_node_title/outline_title",
            },
            "summary": {"type": "string", "description": "章节摘要，可选"},
            "involved_characters": {
                "type": "array",
                "items": {"type": "string"},
                "description": "本章出场的角色名列表",
            },
        },
        required=["title"],
        tool_type="write",
        idempotent=True,
        estimated_cost="free",
        handler_name="create_chapter",
    ),
    ToolDef(
        name="update_chapter",
        description="更新章节。用ID或标题定位。正文将自动修复禁用句式。若正文来自chapter_writer，优先传draft_id/content_ref，避免复制长正文导致截断。",
        input_schema={
            "id": {
                "type": "string",
                "description": "章节ID（优先使用）。也可用 chapter_id/title/chapter_title/outline_node_id 定位",
            },
            "title": {"type": "string", "description": "更新章节标题"},
            "content": {"type": "string", "description": "更新章节正文"},
            "draft_id": {
                "type": "string",
                "description": "chapter_writer返回的草稿ID。优先使用它保存完整正文，避免长正文在工具参数中截断。",
            },
            "content_ref": {
                "type": "string",
                "description": "同draft_id，chapter_writer返回的正文引用。",
            },
            "skip_style_repair": {
                "type": "boolean",
                "description": "是否跳过保存时禁用句式自动修复，默认false。",
            },
            "summary": {"type": "string", "description": "更新章节摘要"},
            "outline_node_id": {"type": "string", "description": "更新关联大纲节点"},
            "involved_characters": {
                "type": "array",
                "items": {"type": "string"},
                "description": "更新出场角色名列表（替换全部关联）",
            },
            "context_manifest_id": {
                "type": "string",
                "description": "Governed task manifest required for MCP formal writes",
            },
        },
        tool_type="write",
        estimated_cost="free",
        handler_name="update_chapter",
    ),
    ToolDef(
        name="list_chapter_versions",
        description="列出章节版本历史。用户说对新章节不满意、想看历史版本、想回退上一版时先用它确认可恢复版本。",
        input_schema={
            "id": {
                "type": "string",
                "description": "章节ID（优先）。也可用 chapter_id/title/chapter_title/outline_node_id 定位",
            },
            "chapter_id": {"type": "string", "description": "章节ID"},
            "title": {"type": "string", "description": "章节标题"},
            "chapter_title": {"type": "string", "description": "章节标题"},
            "outline_node_id": {"type": "string", "description": "关联大纲节点ID"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="list_chapter_versions",
    ),
    ToolDef(
        name="restore_chapter_version",
        description="将章节正文恢复到指定快照，默认回退到上一版，并自动生成新的恢复快照。用户明确说'回退版本''恢复上一版''这章不满意用旧版'时使用。",
        input_schema={
            "id": {
                "type": "string",
                "description": "章节ID（优先）。也可用 chapter_id/title/chapter_title/outline_node_id 定位",
            },
            "chapter_id": {"type": "string", "description": "章节ID"},
            "title": {"type": "string", "description": "章节标题"},
            "chapter_title": {"type": "string", "description": "章节标题"},
            "outline_node_id": {"type": "string", "description": "关联大纲节点ID"},
            "snapshot_id": {"type": "string", "description": "要恢复的快照ID"},
            "version_id": {"type": "string", "description": "同 snapshot_id"},
            "version_number": {"type": "integer", "description": "要恢复的版本号，例如 1"},
            "target": {"type": "string", "description": "previous/first/latest，默认 previous"},
        },
        tool_type="write",
        writes_project_data=True,
        risk_level="medium",
        estimated_cost="free",
        handler_name="restore_chapter_version",
    ),
    ToolDef(
        name="diff_chapter_versions",
        description="对比章节两个历史版本的正文差异。需要 from_snapshot_id/to_snapshot_id 或 from_version/to_version。",
        input_schema={
            "id": {
                "type": "string",
                "description": "章节ID（优先）。也可用 chapter_id/title/chapter_title/outline_node_id 定位",
            },
            "chapter_id": {"type": "string", "description": "章节ID"},
            "title": {"type": "string", "description": "章节标题"},
            "from_snapshot_id": {"type": "string", "description": "起始快照ID"},
            "to_snapshot_id": {"type": "string", "description": "目标快照ID"},
            "from_version": {"type": "integer", "description": "起始版本号"},
            "to_version": {"type": "integer", "description": "目标版本号"},
        },
        tool_type="read",
        estimated_cost="free",
        handler_name="diff_chapter_versions",
    ),
    ToolDef(
        name="delete_chapter",
        description="删除章节。自动回退该章节中角色的状态变更。用ID或标题定位。",
        input_schema={
            "id": {
                "type": "string",
                "description": "章节ID（优先使用）。也可用 chapter_id/title/chapter_title 定位",
            }
        },
        tool_type="write",
        requires_confirmation=True,
        estimated_cost="free",
        handler_name="delete_chapter",
    ),
)


__all__ = ["TOOL_DEFINITIONS"]
